import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { priceRules } from '../lib/priceRules';
import { PriceCalculator } from '../lib/priceCalculator';
import { useRef, useState } from 'react';

export default function Home({}) {
  const calcRef = useRef(new PriceCalculator(priceRules));
  const [total, setTotal] = useState(0);

  const onAppendButtonClick = (key: String) => {
    calcRef.current.append(key);
    setTotal(calcRef.current.getTotal());
  };

  const onClearButtonClick = () => {
    calcRef.current.clear();
    setTotal(calcRef.current.getTotal());
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <div className={styles.heading}>Price Rules (per quantity)</div>
          <div className={styles.priceRules}>{JSON.stringify(priceRules, null, 2)}</div>
        </div>
        <div>
          <div className={styles.heading}>
            Current State
            {calcRef.current.items.length ? (
              <a style={{ marginLeft: 8 }} href="javascript:void(0)" onClick={() => onClearButtonClick()}>
                Clear
              </a>
            ) : null}
          </div>
          <div className={styles.buttonContainer}>
            {Object.keys(priceRules).map((x) => (
              <button key={x} className={styles.button} onClick={() => onAppendButtonClick(x)}>
                {x}
              </button>
            ))}
          </div>
          <div>{calcRef.current.items}</div>
          <div>Total: {total}</div>
        </div>
      </main>
    </>
  );
}
